ComputerService.MVC/Models/ErrorViewModel.cs
namespace ComputerService.MVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

ComputerService.MVC/Areas/Identity/Pages/_ViewStart.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ComputerService.MVC.Areas.Identity.Pages
{
    public class ViewStartModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ComputerService.MVC/Controllers/ComputerServiceController.cs
using AutoMapper;
using ComputerService.Application.ComputerService;
using ComputerService.Application.ComputerService.Commands.CreateComputerService;
using ComputerService.Application.ComputerService.Commands.EditComputerService;
using ComputerService.Application.ComputerService.Queries.GetAllComputerServices;
using ComputerService.Application.ComputerService.Queries.GetComputerServiceByEncodedName;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CarWorkshop.MVC.Controllers
{
    public class ComputerServiceController : Controller
    {
        private readonly IMediator _mediator;
        private readonly IMapper _mapper;

        public ComputerServiceController(IMediator mediator, IMapper mapper)
        {
            _mediator = mediator;
            _mapper = mapper;
        }


        public async Task<IActionResult> Index()
        {
            var computerService = await _mediator.Send(new GetAllComputerServicesQuery());
            return View(computerService);
        }


        [Route("ComputerService/{encodedName}/Details")]
        public async Task<IActionResult> Details(string encodedName)
        {
            var dto = await _mediator.Send(new GetComputerServiceByEncodedNameQuery(encodedName));
            return View(dto);
        }


        [Route("ComputerService/{encodedName}/Edit")]
        public async Task<IActionResult> Edit(string encodedName)
        {
            var dto = await _mediator.Send(new GetComputerServiceByEncodedNameQuery(encodedName));

            if (!dto.IsEditable)
            {
                return RedirectToAction("NoAccess", "Home");
            }

            EditComputerServiceCommand model = _mapper.Map<EditComputerServiceCommand>(dto);

            return View(model);
        }

        [HttpPost]
        [Route("ComputerService/{encodedName}/Edit")]
        public async Task<IActionResult> Edit(string encodedName, EditComputerServiceCommand command)
        {
            if (!ModelState.IsValid)
            {
                return View(command);

            }
            await _mediator.Send(command);
            return RedirectToAction(nameof(Index));
        }

        [Authorize]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreateComputerServiceCommand command)
        {
            if (!ModelState.IsValid)
            {
                return View(command);

            }

            await _mediator.Send(command);
            return RedirectToAction(nameof(Index));
        }
    }
}

ComputerService.MVC/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using ComputerService.MVC.Models;

namespace ComputerService.MVC.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }
    public IActionResult About()
    {
        return View();
    }
    public IActionResult Offer() 
    {
        return View();
    }
    public IActionResult Contact()
    {
        return View();
    }
    public IActionResult NoAccess()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

ComputerService.MVC/Views/ComputerService/Create.cshtml
@using ComputerService.Application.ComputerService.Commands.CreateComputerService;

@model CreateComputerServiceCommand
<h1>Create Car Workshop</h1>

<hr />

<div class="row">
    <div class="col-md-4">
        <form action="/ComputerService/Create" method="post">
            <div class="form-group mb-3">
                <label class="control-label" asp-for="Name">Nazwa</label>
                <input class="form-control" type="text" asp-for="Name">
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group mb-3">
                <label class="control-label" asp-for="Description">Opis</label>
                <input class="form-control" type="text" asp-for="Description">
                <span asp-validation-for="Description" class="text-danger"></span>

            </div>

            <div class="form-group mb-3">
                <label class="control-label" asp-for="PhoneNumber">Numer telefonu</label>
                <input class="form-control" type="text" asp-for="PhoneNumber">
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>

            </div>
            <div class="form-group mb-3">
                <label class="control-label" asp-for="Street">Ulica</label>
                <input class="form-control" type="text" asp-for="Street">
            </div>
            <div class="form-group mb-3">
                <label class="control-label" for="City">Miasto</label>
                <input class="form-control" type="text" asp-for="City">
            </div>
            <div class="form-group mb-3">
                <label class="control-label" asp-for="PostalCode">Kod Pocztowy</label>
                <input class="form-control" type="text" asp-for="PostalCode">
            </div>

            <div class="form-group mb-3">
                <input type="submit" value="Zapisz" class="btn btn-primary">
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ComputerService.MVC/Views/ComputerService/Details.cshtml
@model ComputerService.Application.ComputerService.ComputerServiceDto

@{
    ViewData["Title"] = "Details";
}

    <h1>@Model.Name</h1>

<div >
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
           Opis:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            Numer telefonu:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            Ulica:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Street)
        </dd>
        <dt class = "col-sm-2">
            Miasto
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.City)
        </dd>
        <dt class = "col-sm-2">
            Kod pocztowy:
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PostalCode)
        </dd>
    </dl>
</div>
<div >

    @if (Model.IsEditable)
    {
        <a class="btn btn-outline-secondary" asp-controller="ComputerService" asp-action="Edit" asp-route-encodedName="@Model.EncodedName">Edytuj</a>
    }
    <a asp-action="Index" class="btn btn-outline-secondary">Cofnij</a>
</div>

ComputerService.MVC/Views/ComputerService/Edit.cshtml
@model ComputerService.Application.ComputerService.Commands.EditComputerService.EditComputerServiceCommand

@{
    ViewData["Title"] = "Edit";
}

<h1> Edytujesz @Model.Name</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group m-3">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group m-3">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group m-3">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group m-3">
                <label asp-for="Street" class="control-label"></label>
                <input asp-for="Street" class="form-control" />
                <span asp-validation-for="Street" class="text-danger"></span>
            </div>
            <div class="form-group m-3">
                <label asp-for="City" class="control-label"></label>
                <input asp-for="City" class="form-control" />
                <span asp-validation-for="City" class="text-danger"></span>
            </div>
            <div class="form-group m-3">
                <label asp-for="PostalCode" class="control-label"></label>
                <input asp-for="PostalCode" class="form-control" />
                <span asp-validation-for="PostalCode" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div class="mt -3">
    <a asp-action="Index" class="btn btn-secondary">Cofnij</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

ComputerService.MVC/Views/ComputerService/Index.cshtml
@model IEnumerable<ComputerService.Application.ComputerService.ComputerServiceDto>

@{
    ViewData["Title"] = "Index";
}

<h1>Computer Services</h1>

<p>
    <a asp-action="Create" class="btn btn-secondary">Create New</a>
</p>
<div class="row">
    @foreach (var item in Model)
    {
        <div class="card m-3" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">@item.Name</h5>
                <h6 class="card-subtitle mb-2 text-muted">@item.PhoneNumber</h6>
                <p class="card-text">@item.Description</p>
                <a  class="btn btn-primary" asp-controller="ComputerService" asp-action="Details" asp-route-encodedName="@item.EncodedName">Szczegóły</a>

                @if (item.IsEditable)
                {
                    <a class="btn btn-outline-secondary" asp-controller="ComputerService" asp-action="Edit" asp-route-encodedName="@item.EncodedName">Edytuj</a>
                }
                
            </div>
        </div>
    }
</div>

ComputerService.MVC/Views/Home/About.cshtml
@{
}
<div class="text-center">
    <h1>O Nas</h1><br>
    <div class="row">
        <div class="col">

        </div>
        <div class="col-8">
            <p>
                Firma specjalizuje się w szeroko pojmowanej obsłudze IT, świadczonej głównie dla sektora małych i średnich przedsiębiorstw oraz klientów indywidualnych.
                Zakres naszej oferty jest kompleksowy, a realizowane przez nas usługi informatyczne są zawsze na najwyższym poziomie. Analizujemy potrzeby Klienta i prezentujemy kilka
                wariantów technologii oraz narzędzi, które są najlepszym rozwiązaniem dla jego biznesu.<br />
                Powierzenie nam zadań z zakresu IT, to nie tylko oszczędność, ale przede wszystkim możliwość skupienia się w pełni na prowadzeniu biznesu.
                Usługi informatyczne realizowane przez naszą firmę to doskonały wybór. Nie zwlekaj i skorzystaj z usług certyfikowanych specjalistów z wieloletnim doświadczeniem w branży.
            </p>
        </div>
        <div class="col">
        </div>
  
    </div>
    <img src="~/images/serwis.jpg" class="img-fluid" alt="nima" style="width:700px; height:400px;" >
</div>

ComputerService.MVC/Views/Home/Contact.cshtml
@{

}
<div class=" mr-0 p-0">
    <div class="text-center">
        <h1>Formularz kontaktowy</h1>
    </div>
    <div class="row mt-5">
        <div class="col-6 text-center">
                Jeżeli masz pytania, z chęcią na nie odpowiemy. Aby skontaktować się z nami, <br />użyj danych ze stopki strony lub wyślij zapytanie za pomocą formularza kontaktowego.
        </div>
        <div class="col-6">
            <form action="mailto:mail@mail.com" method="post" enctype="text/plain">
                <div class="mb-3">
                    <label for="name" class="form-label">Imię</label>
                    <input class="form-control" id="name" placeholder="Imię" style="width:80%">
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlInput1" class="form-label">Email address</label>
                    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="Adres e-mail" style="width:80%">
                </div>
                <div class="mb-3">
                    <label for="exampleFormControlTextarea1" class="form-label">Treść</label>
                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Treść" style="width:80%"></textarea>
                </div>
                <input type="submit" class="btn btn-outline-secondary" value="Wyślij formularz">
                <input type="reset" class="btn btn-outline-secondary" value="Wyczyść dane">
            </form>
        </div>
    </div>
</div>

ComputerService.MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";

}
<div id="carouselExampleCaptions" class="carousel slide" style="width:100%;">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="~/images/serwis-komputerow.jpg" class="d-block w-100" alt="nima" style="height: 500px;">
            <div class="carousel-caption d-none d-md-block ">
                <h5>Serwis Konputerowy</h5>
                <p>Oferujemy profesjonalne obsługę firm i klientów indywidualnych.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="~/images/zadowolony.jpg" class="d-block w-100" alt="nima" style="height: 500px;">
            <div class="carousel-caption d-none d-md-block">
                <h5>Zadowoleni klienci</h5>
                <p>Zawsze dokładdamy wszelkich starań aby każdy klient był zadowolny z naszych usług </p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="~/images/naprawa-zdalna.jpg" class="d-block w-100" alt="nima" style="height: 500px;">
            <div class="carousel-caption d-none d-md-block">
                <h5>Naprawa bez wychodzenia z domu</h5>
                <p>Dojazd do domu klienta w obszarze 50 km od zakładu jest w standardzie.</p>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>
<div class="row row-cols-1 row-cols-md-2 g-4 mt-1">
    <div class="col">
        <a asp-area="" asp-controller="Home" asp-action="Contact" class="text-black" style="text-decoration: none;">
            <div class="card">
                <img src="~/images/service.jpg" class="card-img-top" alt="nima" style="height:500px">
                <div class="card-body">
                    <h5 class="card-title">Kontakt</h5>
                    <p class="card-text">Jeśli masz jakieś pytania skontaktuj sie z nami</p>
                </div>
            </div>
        </a>
    </div>
    <div class="col">
        <a asp-area="" asp-controller="Home" asp-action="Contact" class="text-black" style="text-decoration: none; ">
            <div class="card">
                <img src="~/images/pomoczdalna.png" class="card-img-top" alt="nima" style="height:500px">
                <div class="card-body">
                    <h5 class="card-title">Zdalna pomoc</h5>
                    <p class="card-text">Jeżęli interesuje cię zdalna pomoc zadzwoń do konsultanta</p>
                </div>
            </div>
        </a>
    </div>
    <div class="col">
        <a asp-area="" asp-controller="Home" asp-action="Offer" class="text-black" style="text-decoration: none; ">
            <div class="card">
                <img src="~/images/nvidia.jpg" class="card-img-top" alt="nima" style="height:500px">
                <div class="card-body">
                    <h5 class="card-title">Wymiana podzespołów</h5>
                    <p class="card-text">Jeżeli interesuje cię wymiana jakiegoś podzespołu sprawdź czy oferujemy takie usługi</p>
                </div>
            </div>
        </a>
    </div>
    <div class="col">
        <a asp-area="" asp-controller="Home" asp-action="Offer" class="text-black" style="text-decoration: none; ">
            <div class="card">
                <img src="~/images/data-recovery.jpg" class="card-img-top" alt="nima" style="height:500px">
                <div class="card-body">
                    <h5 class="card-title">Odzyskiwanie danych</h5>
                    <p class="card-text">Jeśli interesuje cię odzyskiwanie danych z dysku bądź trwałe usuwanie danych sprawdź ofertę</p>
                </div>
            </div>
        </a>
    </div>
</div>

ComputerService.MVC/Views/Home/NoAccess.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<h1>Nie masz dostępu do tego zasobu</h1>

ComputerService.MVC/Views/Home/Offer.cshtml
@{
}
<div class="text-center mb-5">
    <h1>Oferty</h1>
</div>
<div class="container text-left">
    <div class="row">
        <div class="col">
            <h3>Serwis komputerowy</h3><br />
            Diagnoza, naprawa oraz konserwacja komputerów i laptopów.<br />
            <ul>
                <li>Diagnostyka sprzętu</li>
                <li>Naprawa konputerów </li>
                <li>Naprawa drukarek</li>
                <li>Pomoc przy zakupie laptopa badź komputera</li>
                <li>Czyszczenie i konserwacja systemów chłodzenia laptopa</li>
                <li>Wymiana podzespołów</li>
                <li>Modernizacja sprzętu</li>
                <li>Wymiana past oraz taśm termoprzewodzących układu chłodzenia</li>
            </ul>
        </div>
        <div class="col">
            <img src="~/images/naprawa.png" class="img-fluid" alt="nima">
        </div>
    </div>
    <div class="row mt-5">
        <div class="col">
            <img src="~/images/dysk.jpg" class="img-fluid" alt="nima">
        </div>
        <div class="col">
            <h3>Dodatkowe usługi</h3><br />
            Podejmiemy się każdego zadania związanego z IT.<br />
            <ul>
                <li>Odzyskiwanie danych</li>
                <li>Składanie komputerów do określonych wymagań klienta</li>
                <li>Zdejmowanie zabezpieczeń</li>
                <li>Audyt infrastruktury informatycznej</li>
                <li>Tworzenie stron internetowych</li>
            </ul>
        </div> 
    </div>
</div>

ComputerService.MVC/Views/Shared/_Layout.cshtml
@{
    var action = ViewContext.RouteData.Values["Action"]?.ToString();
    var controller = ViewContext.RouteData.Values["Controller"]?.ToString();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>ComputerService</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ComputerService.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ComputerService</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark @(controller=="Home"&&action=="Index"?"Active":"") " asp-area="" asp-controller="Home" asp-action="Index">Strona główna</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark @(controller=="ComputerService"&&action=="Index"?"action":"")" asp-area="" asp-controller="ComputerService" asp-action="Index">Aktualne zgłoszenia</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark @(controller=="Home"&&action=="Offer"?"action":"")" asp-area="" asp-controller="Home" asp-action="Offer">Oferta</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark @(controller=="Home"&&action=="About"?"action":"")" asp-area="" asp-controller="Home" asp-action="About">O nas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark @(controller=="Home"&&action=="Contact"?"action":"")" asp-area="" asp-controller="Home" asp-action="Contact">Kontakt</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top  bg-primary ">
        <div class="container text-white">
            <div class="container text-left">
                <div class="row">
                    <div class="col mb-4 mt-4">
                        <h3>Kontakt</h3><br/>
                        Konrad Boroń<br/>
                        tel.111222333<br/>
                        e-mail: email@email.pl<br/>
                        Adres: Adres ul. adresowa 21
                    </div>
                    <div class="col mt-4 mb-4">
                        <h3>Odnośniki</h3> <br />
                        <a asp-area="" asp-controller="Home" asp-action="Index" class="text-white" style="text-decoration: none;">Strona główna</a><br />
                        <a asp-area="" asp-controller="Home" asp-action="Privacy" class="text-white" style="text-decoration: none;">Prywatność</a><br />
                        <a asp-area="" asp-controller="Home" asp-action="Offer" class="text-white" style="text-decoration: none;">Oferta</a><br />
                        <a asp-area="" asp-controller="Home" asp-action="About" class="text-white" style="text-decoration: none;">O nas</a><br />
                        <a asp-area="" asp-controller="Home" asp-action="Contact" class="text-white" style="text-decoration: none;">Kontakt</a><br />

                    </div>
                    <div class="col mt-4">
                        <h3>Godziny otwarcia</h3><br />
                        Poniedziałek - Piątek &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; 8:00-16:00 <br />
                        Sobota &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; 10:00-14:00<br />
                        Niedziela &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Zamknięte
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>